/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.edu.ups.vista;

import ec.edu.ups.controladorDirectorio.ControladorDirectorio;
import java.awt.PopupMenu;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author braya
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    private ControladorDirectorio ctrlDirectorio;
    private DefaultListModel listar;
    
    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
        ctrlDirectorio = new ControladorDirectorio(txtRuta.getText());
        listar = new DefaultListModel();
    }

    private DefaultListModel listaDirectorios(){
        ArrayList lista = (ArrayList) ctrlDirectorio.listarArchivos(txtRuta.getText());
        for (Object archivos : lista) {
            
        }
        return listar;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        txtRuta = new javax.swing.JTextField();
        btnListarDi = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListDirectorios = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        menuItemCrear = new javax.swing.JMenuItem();
        saveAsMenuItem = new javax.swing.JMenuItem();
        saveMenuItem = new javax.swing.JMenuItem();
        exitMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gestion de Directorios");

        desktopPane.setName(""); // NOI18N
        desktopPane.add(txtRuta);
        txtRuta.setBounds(330, 60, 230, 24);

        btnListarDi.setText("Listar Directorios");
        btnListarDi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarDiActionPerformed(evt);
            }
        });
        desktopPane.add(btnListarDi);
        btnListarDi.setBounds(190, 130, 129, 32);

        jButton1.setText("Listar Archivos Ocultos");
        desktopPane.add(jButton1);
        jButton1.setBounds(360, 130, 163, 32);

        jButton2.setText("Listar Directorios Ocultos");
        desktopPane.add(jButton2);
        jButton2.setBounds(560, 130, 180, 32);

        jListDirectorios.setAutoscrolls(false);
        jScrollPane1.setViewportView(jListDirectorios);

        desktopPane.add(jScrollPane1);
        jScrollPane1.setBounds(30, 200, 380, 360);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane3.setViewportView(jTextArea1);

        desktopPane.add(jScrollPane3);
        jScrollPane3.setBounds(460, 240, 290, 260);

        jLabel1.setText("Ingrese ruta");
        desktopPane.add(jLabel1);
        jLabel1.setBounds(230, 60, 90, 16);

        jButton3.setText("Mostrar Informacion");
        desktopPane.add(jButton3);
        jButton3.setBounds(120, 570, 180, 32);

        fileMenu.setMnemonic('f');
        fileMenu.setText("Gestionar Directorios");

        menuItemCrear.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        menuItemCrear.setMnemonic('o');
        menuItemCrear.setText("Crear");
        menuItemCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemCrearActionPerformed(evt);
            }
        });
        fileMenu.add(menuItemCrear);

        saveAsMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        saveAsMenuItem.setMnemonic('a');
        saveAsMenuItem.setText("Eliminar");
        fileMenu.add(saveAsMenuItem);

        saveMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_MASK));
        saveMenuItem.setMnemonic('s');
        saveMenuItem.setText("Renombrar");
        fileMenu.add(saveMenuItem);

        exitMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ESCAPE, java.awt.event.InputEvent.CTRL_MASK));
        exitMenuItem.setMnemonic('x');
        exitMenuItem.setText("Salir");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(exitMenuItem);

        menuBar.add(fileMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 803, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 620, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitMenuItemActionPerformed

    private void menuItemCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemCrearActionPerformed
        // TODO add your handling code here:
        String crearDirectorio = "";
        crearDirectorio = JOptionPane.showInputDialog("Ingrese nombre de directorio a crear");
        //System.out.println(crearDirectorio);
        ctrlDirectorio.crearDirectorio(crearDirectorio);
        if (!crearDirectorio.equals("") && !txtRuta.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Se ha creado satisfactoriamente el directorio");
        } else {
            
            if (txtRuta.getText().equals("")) {
                JOptionPane.showMessageDialog(this, "Ingrese una ruta para crear un nuevo directorio");
            } else if (crearDirectorio.equals("")) {
                JOptionPane.showMessageDialog(this, "No se puede crear ningun directorio no se ha ingresado nada");
            } else{
                JOptionPane.showMessageDialog(this, "Ingrese una ruta y un nombre de directorio");
            }
        }
    }//GEN-LAST:event_menuItemCrearActionPerformed

    private void btnListarDiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarDiActionPerformed
        // TODO add your handling code here:
        String ruta = txtRuta.getText();
        if(ruta.equals("")){
            JOptionPane.showMessageDialog(this, "Ingrese una ruta");
        }else{
            ctrlDirectorio.listarArchivos(txtRuta.getText());
            
            //listaDirectorios();
        }
    }//GEN-LAST:event_btnListarDiActionPerformed

//    public void listarArchivos() {
//        ctrlDirectorio.listarArchivos(txtRuta.getText());
//    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnListarDi;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JList<String> jListDirectorios;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem menuItemCrear;
    private javax.swing.JMenuItem saveAsMenuItem;
    private javax.swing.JMenuItem saveMenuItem;
    private javax.swing.JTextField txtRuta;
    // End of variables declaration//GEN-END:variables

}
